# Numpy

### 코드로 방정식 표현하기

In [1]:
coefficient_matrix = [[2, 2, 1], [2, -1, 2], [1, -1, 2]]
constant_vector = [9, 6, 5]

In [1]:
import numpy as np

In [3]:
test_array = np.array([1, 4, 5, 8], float)
print(test_array)
type(test_array[3])

[1. 4. 5. 8.]


numpy.float64

In [4]:
test_array = np.array(['1', '2', 5.0, 8], float)
test_array

array([1., 2., 5., 8.])

In [5]:
type(test_array[3])

numpy.float64

In [6]:
print(type(test_array[3]))
print(test_array.dtype)
print(test_array.shape)

<class 'numpy.float64'>
float64
(4,)


In [3]:
arr = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

# reshape

In [4]:
np.array(arr).shape

(2, 4)

In [5]:
np.array(arr).reshape(4, 2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [6]:
np.array(arr).reshape(8, -1)

array([[1],
       [2],
       [3],
       [4],
       [1],
       [2],
       [3],
       [4]])

# flatten

In [7]:
np.array(arr).flatten()

array([1, 2, 3, 4, 1, 2, 3, 4])

# indexing & slicing

In [8]:
arr[0, 0] = 3

In [9]:
arr

array([[3, 2, 3, 4],
       [1, 2, 3, 4]])

In [10]:
arr[:, 2:]

array([[3, 4],
       [3, 4]])

In [11]:
arr[1, 1:3]

array([2, 3])

In [12]:
arr1 = np.arange(100).reshape(10,10)

In [13]:
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

# zeros

In [18]:
np.zeros((2, 10)) # 0을 스칼라로 하는 매트릭스 생성

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones((2, 10)) # 1을 스칼라로 하는 매트릭스 생성

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
np.ones_like(arr) # arr과 같은 모양의 1을 스칼라로 하는 매트릭스 생성

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
np.zeros_like(arr)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [49]:
np.empty(shape=(10,), dtype = np.int8)

array([   0,    0,    0,    0,    0,    0,    0,    0, -112,  -75],
      dtype=int8)

In [50]:
np.identity(n=3, dtype=np.int8) # 단위행렬(i 행렬) 생성

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [51]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.eye(3, 5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
mat = np.arange(49).reshape(7,7)

In [58]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [59]:
np.diag(mat, k=2)

array([ 2, 10, 18, 26, 34])

# random sampling

In [60]:
np.random.normal(0, 1, 10).reshape(2, 5)

array([[-0.9073619 , -0.27890177,  1.02897054,  0.02493181, -0.31757888],
       [-1.04256943, -0.15680146,  1.27609362, -1.39802241,  2.20100143]])

In [65]:
np.random.binomial(100, 0.67)

70

In [66]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [67]:
mat.mean(axis=1)

array([ 3., 10., 17., 24., 31., 38., 45.])

# concatenate

In [71]:
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])

In [73]:
np.concatenate((a, b), axis = 0)

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

In [77]:
b = b[np.newaxis, :]
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

# 연산

In [78]:
scalar = 3

In [79]:
mat + scalar

array([[ 3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51]])

In [82]:
arr = np.arange(1, 11).reshape(5, 2)

In [83]:
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [86]:
arr1 = np.array([2, 3])

In [87]:
arr - arr1

array([[-1, -1],
       [ 1,  1],
       [ 3,  3],
       [ 5,  5],
       [ 7,  7]])

# all & any

In [88]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
np.any(a>5), np.any(a<0) # 하나라도 만족하면 true

(True, False)

In [90]:
a < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [92]:
np.all(a>-1)

True

In [93]:
np.where(a > 0, 3, 2)

array([2, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [94]:
a = np.arange(10)
np.where(a>5) # true인 인덱스 값 반환

(array([6, 7, 8, 9], dtype=int64),)

In [98]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [99]:
np.isinf(a)

array([False, False,  True])

In [100]:
a = np.array([1, 2, 34567,2356,23,3515])
a.argsort()

array([0, 1, 4, 3, 5, 2], dtype=int64)

### boolean indexing

In [103]:
condition = a < 40

In [104]:
a[condition] # 조건에 true인 값 반환

array([ 1,  2, 23])

### fancy indexing

In [105]:
a = np.array([2, 4, 6, 8])
b = np.array([0, 0, 1 ,3, 2, 1], int)
a[b]

array([2, 2, 4, 8, 6, 4])